# Generated by Django 2.2.1 on 2020-05-26 14:29

import ckeditor_uploader.fields
from django.db import migrations, models
import read.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': '文章标签',
                'verbose_name_plural': '文章标签',
                'db_table': 'ArticleTag',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('published', models.DateField(auto_now_add=True)),
                ('tagName', models.ManyToManyField(to='article.Tag')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': '文章详情',
                'db_table': 'Article',
            },
            bases=(models.Model, read.models.ReadNumMethod),
        ),
    ]
