# Generated by Django 2.1.5 on 2020-05-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200511_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tagName',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
