# Generated by Django 2.2.1 on 2020-06-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likerecord',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='LikeCount',
        ),
    ]
